version: "3.7"
services:
  nextim:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nextim
    volumes:
      - ./:/usr/src
    ports:
      - 3000:3000
    expose:
      - 3000
volumes: 
  next:
